const constants={
    LOAD_POSTS:'LOAD_POSTS',
    ADD_POST:'ADD_POST',
    ADD_POST_PANEL:'ADD_POST_PANEL',
    SORT:'SORT',
    SORT_TYPES:{
        SORT_BY_DATE:'SORT_BY_DATE',
        SORT_BY_REIT:'SORT_BY_REIT'
    },
    SHOW_HINT:'SHOW_HINT',
    LOGGING_IN:'LOGGED_IN',
    EXIT:'EXIT',
    RESET_POSTS:'RESET_POSTS',
    LIKE:'LIKE',
    DELETE_LIKE:'DELETE_LIKE',
    SAVE:'SAVE',
    COMMENTS_HIDDEN:'COMMENTS_HIDDEN',
    COMMENTS_SHOWN:'COMMENTS_SHOWN',
    LOAD_COMMENTS:'LOAD_COMMENTS',
    ADD_COMMENT:'ADD_COMMENT',
    DELETE_SAVE:'DELETE_SAVE',
    REGISTRATION_LIST:'REGISTRATION_LIST',
    AUTHORIZATION_LIST:'AUTHORIZATION',
    USER_PANEL_TYPES:{
        LOGGED_IN:'LOGGED_IN',
        AUTHORIZATION:'AUTHORIZATION',
        REGISTRATION:'REGISTRATION'
    },
    GET_INFO_ABOUT_USER:'GET_INFO_ABOUT_USER',
    ADD_USER:'ADD_USER'
};

export default constants;