const constants={
    LOAD_POSTS:'LOAD_POSTS',
    SORT:'SORT',
    SORT_TYPES:{
        SORT_BY_DATE:'SORT_BY_DATE',
        SORT_BY_REIT:'SORT_BY_REIT'
    },
    SHOW_HINT:'SHOW_HINT',
    LOGGING_IN:'LOGGED_IN',
    EXIT:'EXIT',
    REGISTRATION_LIST:'REGISTRATION_LIST',
    AUTHORIZATION_LIST:'AUTHORIZATION',
    USER_PANEL_TYPES:{
        LOGGED_IN:'LOGGED_IN',
        AUTHORIZATION:'AUTHORIZATION',
        REGISTRATION:'REGISTRATION'
    },
    GET_INFO_ABOUT_USER:'GET_INFO_ABOUT_USER',
    ADD_USER:'ADD_USER'
};

export default constants;